ALTER TABLE resources
  DROP COLUMN IF EXISTS street,
  DROP COLUMN IF EXISTS number,
  DROP COLUMN IF EXISTS block,
  DROP COLUMN IF EXISTS flat,
  DROP COLUMN IF EXISTS zip_code,
  DROP COLUMN IF EXISTS city,
  DROP COLUMN IF EXISTS county,
  DROP COLUMN IF EXISTS country,
  DROP COLUMN IF EXISTS driving_licence,
  DROP COLUMN IF EXISTS car,
  DROP COLUMN IF EXISTS availability;

DROP TYPE IF EXISTS availability_status;
