// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type AllocationSummary struct {
	Free           int                   `json:"free"`
	Assigned       int                   `json:"assigned"`
	Blacklisted    int                   `json:"blacklisted"`
	ByAvailability []*AvailabilityBucket `json:"byAvailability"`
}

type AuthPayload struct {
	Token string    `json:"token"`
	User  *AuthUser `json:"user"`
}

type AuthUser struct {
	ID          string `json:"id"`
	Username    string `json:"username"`
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
}

type AvailabilityBucket struct {
	Availability *Availability `json:"availability,omitempty"`
	Count        int           `json:"count"`
}

type CreateCvTemplateInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	HTML        string  `json:"html"`
	IsDefault   *bool   `json:"isDefault,omitempty"`
}

type CreateLanguageInput struct {
	Name string `json:"name"`
}

type CreateResourceActivityInput struct {
	ResourceID  string  `json:"resourceId"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	StartDate   string  `json:"startDate"`
	EndDate     string  `json:"endDate"`
}

type CvTemplate struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	HTML        string  `json:"html"`
	IsDefault   bool    `json:"isDefault"`
	CreatedAt   string  `json:"createdAt"`
	ModifiedAt  string  `json:"modifiedAt"`
}

// A language in the catalog, shared across all resources.
type Language struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type LoginInput struct {
	UsernameOrEmail string `json:"usernameOrEmail"`
	Password        string `json:"password"`
}

type MatchFilter struct {
	SkillIds     []string       `json:"skillIds,omitempty"`
	Availability []Availability `json:"availability,omitempty"`
	OnlyFree     *bool          `json:"onlyFree,omitempty"`
	Search       *string        `json:"search,omitempty"`
}

type Mutation struct {
}

// A candidate project for a resource, ranked by how many of the project's still
// unfilled skill requirements the resource covers.
type ProjectMatch struct {
	Project          *Project `json:"project"`
	MatchScore       int      `json:"matchScore"`
	MatchingSkillIds []string `json:"matchingSkillIds"`
	OpenPositions    int      `json:"openPositions"`
}

type ProjectMatchFilter struct {
	Status   []ProjectStatus `json:"status,omitempty"`
	Search   *string         `json:"search,omitempty"`
	OnlyOpen *bool           `json:"onlyOpen,omitempty"`
}

type ProjectStaffing struct {
	ProjectID     string              `json:"projectId"`
	ProjectName   string              `json:"projectName"`
	Status        ProjectStatus       `json:"status"`
	TotalNeeded   int                 `json:"totalNeeded"`
	TotalAssigned int                 `json:"totalAssigned"`
	Requirements  []*SkillRequirement `json:"requirements"`
}

type Query struct {
}

// A rendered CV. `html` is always populated and is the single source both
// output formats derive from. `docxBase64` is only populated when the
// requested format is DOCX.
type RenderedCv struct {
	ResourceID string  `json:"resourceId"`
	TemplateID string  `json:"templateId"`
	FileName   string  `json:"fileName"`
	HTML       string  `json:"html"`
	DocxBase64 *string `json:"docxBase64,omitempty"`
}

type ReportSummary struct {
	TotalProjects        int     `json:"totalProjects"`
	ActiveProjects       int     `json:"activeProjects"`
	TotalResources       int     `json:"totalResources"`
	OpenPositions        int     `json:"openPositions"`
	FillRate             float64 `json:"fillRate"`
	FullyStaffedProjects int     `json:"fullyStaffedProjects"`
}

type Reports struct {
	Summary         *ReportSummary     `json:"summary"`
	ProjectStaffing []*ProjectStaffing `json:"projectStaffing"`
	SkillDemand     []*SkillDemand     `json:"skillDemand"`
	Allocation      *AllocationSummary `json:"allocation"`
}

type ResourceActivity struct {
	ID          string  `json:"id"`
	ResourceID  string  `json:"resourceId"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	StartDate   string  `json:"startDate"`
	EndDate     string  `json:"endDate"`
}

type ResourceAllocation struct {
	Resource     *Resource `json:"resource"`
	ProjectCount int       `json:"projectCount"`
	ProjectNames []string  `json:"projectNames"`
}

// A language a resource knows, with their proficiency in it.
type ResourceLanguage struct {
	ID         string        `json:"id"`
	ResourceID string        `json:"resourceId"`
	LanguageID string        `json:"languageId"`
	Name       string        `json:"name"`
	Level      LanguageLevel `json:"level"`
}

// A candidate resource for a project, ranked by how many of the project's still
// unfilled skill requirements it covers.
type ResourceMatch struct {
	Resource             *Resource `json:"resource"`
	MatchScore           int       `json:"matchScore"`
	MatchingSkillIds     []string  `json:"matchingSkillIds"`
	AssignedProjectCount int       `json:"assignedProjectCount"`
}

type SetProjectRequirementInput struct {
	ProjectID   string `json:"projectId"`
	SkillID     string `json:"skillId"`
	NeededCount int    `json:"neededCount"`
}

type SetResourceLanguageInput struct {
	ResourceID string        `json:"resourceId"`
	LanguageID string        `json:"languageId"`
	Level      LanguageLevel `json:"level"`
}

type SkillDemand struct {
	SkillID        string `json:"skillId"`
	SkillName      string `json:"skillName"`
	Demand         int    `json:"demand"`
	Supply         int    `json:"supply"`
	AssignedSupply int    `json:"assignedSupply"`
}

type UpdateCvTemplateInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	HTML        string  `json:"html"`
	IsDefault   bool    `json:"isDefault"`
}

type UpdateProjectInput struct {
	Name          string        `json:"name"`
	ContactPerson string        `json:"contactPerson"`
	Phone         *string       `json:"phone,omitempty"`
	Email         *string       `json:"email,omitempty"`
	Status        ProjectStatus `json:"status"`
}

type UpdateResourceActivityInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	StartDate   string  `json:"startDate"`
	EndDate     string  `json:"endDate"`
}

type UpdateResourceInput struct {
	Name           string        `json:"name"`
	Birthdate      *string       `json:"birthdate,omitempty"`
	Phone          *string       `json:"phone,omitempty"`
	Email          *string       `json:"email,omitempty"`
	Street         *string       `json:"street,omitempty"`
	Number         *string       `json:"number,omitempty"`
	Block          *string       `json:"block,omitempty"`
	Flat           *string       `json:"flat,omitempty"`
	ZipCode        *string       `json:"zipCode,omitempty"`
	City           *string       `json:"city,omitempty"`
	County         *string       `json:"county,omitempty"`
	Country        *string       `json:"country,omitempty"`
	DrivingLicence bool          `json:"drivingLicence"`
	Car            bool          `json:"car"`
	Availability   *Availability `json:"availability,omitempty"`
}

type Availability string

const (
	AvailabilityAsap       Availability = "ASAP"
	AvailabilityOneWeek    Availability = "ONE_WEEK"
	AvailabilityTwoWeeks   Availability = "TWO_WEEKS"
	AvailabilityThreeWeeks Availability = "THREE_WEEKS"
)

var AllAvailability = []Availability{
	AvailabilityAsap,
	AvailabilityOneWeek,
	AvailabilityTwoWeeks,
	AvailabilityThreeWeeks,
}

func (e Availability) IsValid() bool {
	switch e {
	case AvailabilityAsap, AvailabilityOneWeek, AvailabilityTwoWeeks, AvailabilityThreeWeeks:
		return true
	}
	return false
}

func (e Availability) String() string {
	return string(e)
}

func (e *Availability) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Availability(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Availability", str)
	}
	return nil
}

func (e Availability) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type CvFormat string

const (
	CvFormatPDF  CvFormat = "PDF"
	CvFormatDocx CvFormat = "DOCX"
)

var AllCvFormat = []CvFormat{
	CvFormatPDF,
	CvFormatDocx,
}

func (e CvFormat) IsValid() bool {
	switch e {
	case CvFormatPDF, CvFormatDocx:
		return true
	}
	return false
}

func (e CvFormat) String() string {
	return string(e)
}

func (e *CvFormat) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CvFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CvFormat", str)
	}
	return nil
}

func (e CvFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

// CEFR proficiency levels, plus NATIVE for mother-tongue speakers.
type LanguageLevel string

const (
	LanguageLevelA1     LanguageLevel = "A1"
	LanguageLevelA2     LanguageLevel = "A2"
	LanguageLevelB1     LanguageLevel = "B1"
	LanguageLevelB2     LanguageLevel = "B2"
	LanguageLevelC1     LanguageLevel = "C1"
	LanguageLevelC2     LanguageLevel = "C2"
	LanguageLevelNative LanguageLevel = "NATIVE"
)

var AllLanguageLevel = []LanguageLevel{
	LanguageLevelA1,
	LanguageLevelA2,
	LanguageLevelB1,
	LanguageLevelB2,
	LanguageLevelC1,
	LanguageLevelC2,
	LanguageLevelNative,
}

func (e LanguageLevel) IsValid() bool {
	switch e {
	case LanguageLevelA1, LanguageLevelA2, LanguageLevelB1, LanguageLevelB2, LanguageLevelC1, LanguageLevelC2, LanguageLevelNative:
		return true
	}
	return false
}

func (e LanguageLevel) String() string {
	return string(e)
}

func (e *LanguageLevel) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LanguageLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LanguageLevel", str)
	}
	return nil
}

func (e LanguageLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
