package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"backend/graph/model"
	"context"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	payload, err := r.AuthSvc.Login(ctx, input.UsernameOrEmail, input.Password)
	if err != nil {
		if gqlErr, ok := err.(*gqlerror.Error); ok {
			return nil, gqlErr
		}
		return nil, gqlerror.Errorf("failed to log in")
	}
	return payload, nil
}
