package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"backend/graph/model"
	"context"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// AddProjectComment is the resolver for the addProjectComment field.
func (r *mutationResolver) AddProjectComment(ctx context.Context, input model.AddCommentInput) (*model.Comment, error) {
	c, err := r.CommentSvc.AddToProject(ctx, input)
	if err != nil {
		return nil, gqlerror.Errorf("failed to add project comment")
	}
	return c, nil
}

// AddResourceComment is the resolver for the addResourceComment field.
func (r *mutationResolver) AddResourceComment(ctx context.Context, input model.AddCommentInput) (*model.Comment, error) {
	c, err := r.CommentSvc.AddToResource(ctx, input)
	if err != nil {
		return nil, gqlerror.Errorf("failed to add resource comment")
	}
	return c, nil
}

// ProjectComments is the resolver for the projectComments field.
func (r *queryResolver) ProjectComments(ctx context.Context, projectID string) ([]*model.Comment, error) {
	comments, err := r.CommentSvc.ListForProject(ctx, projectID)
	if err != nil {
		return nil, gqlerror.Errorf("failed to fetch project comments")
	}
	return comments, nil
}

// ResourceComments is the resolver for the resourceComments field.
func (r *queryResolver) ResourceComments(ctx context.Context, resourceID string) ([]*model.Comment, error) {
	comments, err := r.CommentSvc.ListForResource(ctx, resourceID)
	if err != nil {
		return nil, gqlerror.Errorf("failed to fetch resource comments")
	}
	return comments, nil
}
