package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"backend/graph/model"
	"context"
)

// CreateCvTemplate is the resolver for the createCvTemplate field.
func (r *mutationResolver) CreateCvTemplate(ctx context.Context, input model.CreateCvTemplateInput) (*model.CvTemplate, error) {
	return r.CvSvc.CreateTemplate(ctx, input)
}

// UpdateCvTemplate is the resolver for the updateCvTemplate field.
func (r *mutationResolver) UpdateCvTemplate(ctx context.Context, id string, input model.UpdateCvTemplateInput) (*model.CvTemplate, error) {
	return r.CvSvc.UpdateTemplate(ctx, id, input)
}

// DeleteCvTemplate is the resolver for the deleteCvTemplate field.
func (r *mutationResolver) DeleteCvTemplate(ctx context.Context, id string) (bool, error) {
	return r.CvSvc.DeleteTemplate(ctx, id)
}

// CvTemplates is the resolver for the cvTemplates field.
func (r *queryResolver) CvTemplates(ctx context.Context) ([]*model.CvTemplate, error) {
	return r.CvSvc.ListTemplates(ctx)
}

// CvTemplate is the resolver for the cvTemplate field.
func (r *queryResolver) CvTemplate(ctx context.Context, id string) (*model.CvTemplate, error) {
	return r.CvSvc.GetTemplate(ctx, id)
}

// RenderCv is the resolver for the renderCv field.
func (r *queryResolver) RenderCv(ctx context.Context, resourceID string, templateID string, format model.CvFormat) (*model.RenderedCv, error) {
	return r.CvSvc.Render(ctx, resourceID, templateID, format)
}
