package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"backend/graph/model"
	"context"
)

// CreateLanguage is the resolver for the createLanguage field.
func (r *mutationResolver) CreateLanguage(ctx context.Context, input model.CreateLanguageInput) (*model.Language, error) {
	return r.LanguageSvc.Create(ctx, input)
}

// DeleteLanguage is the resolver for the deleteLanguage field.
func (r *mutationResolver) DeleteLanguage(ctx context.Context, id string) (bool, error) {
	return r.LanguageSvc.Delete(ctx, id)
}

// SetResourceLanguage is the resolver for the setResourceLanguage field.
func (r *mutationResolver) SetResourceLanguage(ctx context.Context, input model.SetResourceLanguageInput) (*model.ResourceLanguage, error) {
	return r.LanguageSvc.Set(ctx, input)
}

// RemoveResourceLanguage is the resolver for the removeResourceLanguage field.
func (r *mutationResolver) RemoveResourceLanguage(ctx context.Context, resourceID string, languageID string) (bool, error) {
	return r.LanguageSvc.Remove(ctx, resourceID, languageID)
}

// Languages is the resolver for the languages field.
func (r *queryResolver) Languages(ctx context.Context) ([]*model.Language, error) {
	return r.LanguageSvc.List(ctx)
}

// ResourceLanguages is the resolver for the resourceLanguages field.
func (r *queryResolver) ResourceLanguages(ctx context.Context, resourceID string) ([]*model.ResourceLanguage, error) {
	return r.LanguageSvc.ListByResource(ctx, resourceID)
}
