package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"backend/graph/generated"
	"backend/graph/model"
	"context"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	p, err := r.ProjectSvc.Create(ctx, input)
	if err != nil {
		return nil, gqlerror.Errorf("failed to create project")
	}
	return p, nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (bool, error) {
	ok, err := r.ProjectSvc.Delete(ctx, id)
	if err != nil {
		return false, gqlerror.Errorf("failed to delete project")
	}
	return ok, nil
}

// ToggleProjectSkill is the resolver for the toggleProjectSkill field.
func (r *mutationResolver) ToggleProjectSkill(ctx context.Context, projectID string, skillID string) (*model.Project, error) {
	p, err := r.ProjectSvc.ToggleSkill(ctx, projectID, skillID)
	if err != nil {
		return nil, gqlerror.Errorf("failed to toggle project skill")
	}
	return p, nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id string, input model.UpdateProjectInput) (*model.Project, error) {
	p, err := r.ProjectSvc.Update(ctx, id, input)
	if err != nil {
		return nil, gqlerror.Errorf("failed to update project")
	}
	return p, nil
}

// SetProjectRequirement is the resolver for the setProjectRequirement field.
func (r *mutationResolver) SetProjectRequirement(ctx context.Context, input model.SetProjectRequirementInput) (*model.Project, error) {
	p, err := r.ProjectSvc.SetRequirement(ctx, input)
	if err != nil {
		return nil, gqlerror.Errorf("failed to set project requirement")
	}
	return p, nil
}

// RemoveProjectRequirement is the resolver for the removeProjectRequirement field.
func (r *mutationResolver) RemoveProjectRequirement(ctx context.Context, projectID string, skillID string) (*model.Project, error) {
	p, err := r.ProjectSvc.RemoveRequirement(ctx, projectID, skillID)
	if err != nil {
		return nil, gqlerror.Errorf("failed to remove project requirement")
	}
	return p, nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*model.Project, error) {
	projects, err := r.ProjectSvc.List(ctx)
	if err != nil {
		return nil, gqlerror.Errorf("failed to fetch projects")
	}
	return projects, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
