package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"backend/graph/model"
	"context"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Reports is the resolver for the reports field.
func (r *queryResolver) Reports(ctx context.Context) (*model.Reports, error) {
	reports, err := r.ReportSvc.Build(ctx, r.ProjectSvc)
	if err != nil {
		return nil, gqlerror.Errorf("failed to build reports")
	}
	return reports, nil
}
