package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"backend/graph/model"
	"context"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateResource is the resolver for the createResource field.
func (r *mutationResolver) CreateResource(ctx context.Context, input model.CreateResourceInput) (*model.Resource, error) {
	res, err := r.ResourceSvc.Create(ctx, input)
	if err != nil {
		return nil, gqlerror.Errorf("failed to create resource")
	}
	return res, nil
}

// UpdateResource is the resolver for the updateResource field.
func (r *mutationResolver) UpdateResource(ctx context.Context, id string, input model.UpdateResourceInput) (*model.Resource, error) {
	res, err := r.ResourceSvc.Update(ctx, id, input)
	if err != nil {
		return nil, gqlerror.Errorf("failed to update resource")
	}
	return res, nil
}

// DeleteResource is the resolver for the deleteResource field.
func (r *mutationResolver) DeleteResource(ctx context.Context, id string) (bool, error) {
	ok, err := r.ResourceSvc.Delete(ctx, id)
	if err != nil {
		return false, gqlerror.Errorf("failed to delete resource")
	}
	return ok, nil
}

// ToggleResourceSkill is the resolver for the toggleResourceSkill field.
func (r *mutationResolver) ToggleResourceSkill(ctx context.Context, resourceID string, skillID string) (*model.Resource, error) {
	res, err := r.ResourceSvc.ToggleSkill(ctx, resourceID, skillID)
	if err != nil {
		return nil, gqlerror.Errorf("failed to toggle resource skill")
	}
	return res, nil
}

// AssignResource is the resolver for the assignResource field.
func (r *mutationResolver) AssignResource(ctx context.Context, projectID string, resourceID string, skillID *string) (*model.Assignment, error) {
	a, err := r.ResourceSvc.Assign(ctx, projectID, resourceID, skillID)
	if err != nil {
		return nil, gqlerror.Errorf("failed to assign resource")
	}
	return a, nil
}

// UnassignResource is the resolver for the unassignResource field.
func (r *mutationResolver) UnassignResource(ctx context.Context, projectID string, resourceID string) (bool, error) {
	ok, err := r.ResourceSvc.Unassign(ctx, projectID, resourceID)
	if err != nil {
		return false, gqlerror.Errorf("failed to unassign resource")
	}
	return ok, nil
}

// BlockResource is the resolver for the blockResource field.
func (r *mutationResolver) BlockResource(ctx context.Context, id string) (*model.Resource, error) {
	res, err := r.ResourceSvc.Block(ctx, id)
	if err != nil {
		return nil, gqlerror.Errorf("failed to block resource")
	}
	return res, nil
}

// Resources is the resolver for the resources field.
func (r *queryResolver) Resources(ctx context.Context) ([]*model.Resource, error) {
	resources, err := r.ResourceSvc.List(ctx)
	if err != nil {
		return nil, gqlerror.Errorf("failed to fetch resources")
	}
	return resources, nil
}

// Resource is the resolver for the resource field.
func (r *queryResolver) Resource(ctx context.Context, id string) (*model.Resource, error) {
	res, err := r.ResourceSvc.GetByID(ctx, id)
	if err != nil {
		return nil, gqlerror.Errorf("failed to fetch resource")
	}
	return res, nil
}

// ProjectAssignments is the resolver for the projectAssignments field.
func (r *queryResolver) ProjectAssignments(ctx context.Context, projectID string) ([]*model.Assignment, error) {
	assignments, err := r.ResourceSvc.ListAssignments(ctx, projectID)
	if err != nil {
		return nil, gqlerror.Errorf("failed to fetch assignments")
	}
	return assignments, nil
}

// MatchResources is the resolver for the matchResources field.
func (r *queryResolver) MatchResources(ctx context.Context, projectID string, filter *model.MatchFilter) ([]*model.ResourceMatch, error) {
	matches, err := r.MatchSvc.Match(ctx, r.ProjectSvc, r.ResourceSvc, projectID, filter)
	if err != nil {
		return nil, gqlerror.Errorf("failed to match resources")
	}
	return matches, nil
}

// ResourceAllocations is the resolver for the resourceAllocations field.
func (r *queryResolver) ResourceAllocations(ctx context.Context) ([]*model.ResourceAllocation, error) {
	allocations, err := r.ResourceSvc.ListAllocations(ctx)
	if err != nil {
		return nil, gqlerror.Errorf("failed to load resource allocations")
	}
	return allocations, nil
}

// MatchProjects is the resolver for the matchProjects field.
func (r *queryResolver) MatchProjects(ctx context.Context, resourceID string, filter *model.ProjectMatchFilter) ([]*model.ProjectMatch, error) {
	matches, err := r.MatchSvc.MatchProjects(ctx, r.ProjectSvc, r.ResourceSvc, resourceID, filter)
	if err != nil {
		return nil, gqlerror.Errorf("failed to match projects")
	}
	return matches, nil
}
