package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"backend/graph/model"
	"context"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateResourceActivity is the resolver for the createResourceActivity field.
func (r *mutationResolver) CreateResourceActivity(ctx context.Context, input model.CreateResourceActivityInput) (*model.ResourceActivity, error) {
	a, err := r.ResourceActivitySvc.Create(ctx, input)
	if err != nil {
		return nil, gqlerror.Errorf("failed to create resource activity")
	}
	return a, nil
}

// UpdateResourceActivity is the resolver for the updateResourceActivity field.
func (r *mutationResolver) UpdateResourceActivity(ctx context.Context, id string, input model.UpdateResourceActivityInput) (*model.ResourceActivity, error) {
	a, err := r.ResourceActivitySvc.Update(ctx, id, input)
	if err != nil {
		return nil, gqlerror.Errorf("failed to update resource activity")
	}
	return a, nil
}

// DeleteResourceActivity is the resolver for the deleteResourceActivity field.
func (r *mutationResolver) DeleteResourceActivity(ctx context.Context, id string) (bool, error) {
	ok, err := r.ResourceActivitySvc.Delete(ctx, id)
	if err != nil {
		return false, gqlerror.Errorf("failed to delete resource activity")
	}
	return ok, nil
}

// ResourceActivities is the resolver for the resourceActivities field.
func (r *queryResolver) ResourceActivities(ctx context.Context, resourceID string) ([]*model.ResourceActivity, error) {
	activities, err := r.ResourceActivitySvc.ListByResource(ctx, resourceID)
	if err != nil {
		return nil, gqlerror.Errorf("failed to fetch resource activities")
	}
	return activities, nil
}
