package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"backend/graph/model"
	"context"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateSkill is the resolver for the createSkill field.
func (r *mutationResolver) CreateSkill(ctx context.Context, input model.CreateSkillInput) (*model.Skill, error) {
	s, err := r.SkillSvc.Create(ctx, input)
	if err != nil {
		return nil, gqlerror.Errorf("failed to create skill")
	}
	return s, nil
}

// DeleteSkill is the resolver for the deleteSkill field.
func (r *mutationResolver) DeleteSkill(ctx context.Context, id string) (bool, error) {
	ok, err := r.SkillSvc.Delete(ctx, id)
	if err != nil {
		return false, gqlerror.Errorf("failed to delete skill")
	}
	return ok, nil
}

// Skills is the resolver for the skills field.
func (r *queryResolver) Skills(ctx context.Context) ([]*model.Skill, error) {
	skills, err := r.SkillSvc.List(ctx)
	if err != nil {
		return nil, gqlerror.Errorf("failed to fetch skills")
	}
	return skills, nil
}
